"""Render the derived counterexamples.

Two negative artifacts are constructed from the positive ones, so the
contrast each demonstrates is true by construction:

- counterexamples/run-unattended.sysml = the committed policy text
  (model/vendor-fraud-review.sysml up to its RunConfigurations package),
  byte-identical, plus counterexamples/run-unattended.tail (three runs
  that must fail satisfy, one per check level).
- counterexamples/track-missing-approval.trig = track/run-001.trig with
  the approvals graph removed: the same record, minus the discharge.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

TRIG_HEADER = """\
# GENERATED by checks/render_counterexamples.py: track/run-001.trig with
# the run:approvals graph removed. Same obligations, same guard results,
# same oracle citations — the only difference is that nothing discharges
# the obligations. Must FAIL shapes/track.shapes.ttl and be caught by
# queries/governance.rq.
"""


SYSML_BANNER = """\
// GENERATED COUNTEREXAMPLE (checks/render_counterexamples.py): the
// committed policy text of model/vendor-fraud-review.sysml, byte-identical,
// plus three runs that must FAIL satisfy — this file is NOT the model.
"""


def render_run_unattended():
    model = (ROOT / "model" / "vendor-fraud-review.sysml").read_text()
    policy = model.split("    package RunConfigurations {")[0]
    tail = (ROOT / "counterexamples" / "run-unattended.tail").read_text()
    return SYSML_BANNER + policy + tail


def render_track_missing_approval():
    source = (ROOT / "track" / "run-001.trig").read_text()
    without, n = re.subn(r"\nrun:approvals \{.*?\n\}\n", "\n", source, flags=re.S)
    assert n == 1, "expected exactly one run:approvals graph in run-001"
    return TRIG_HEADER + without


if __name__ == "__main__":
    (ROOT / "counterexamples" / "run-unattended.sysml").write_text(render_run_unattended())
    (ROOT / "counterexamples" / "track-missing-approval.trig").write_text(
        render_track_missing_approval()
    )
    print("rendered counterexamples/run-unattended.sysml and track-missing-approval.trig")
